// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhgnzccfvybxhwsfwaqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZ256Y2NmdnlieGh3c2Z3YXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjY5NzEsImV4cCI6MjA1OTcwMjk3MX0.csG42bmizsRubDTftkXs9ga6EWUhMgIymxNok7Kti7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);